- cell/color.go
- container/container.go
- draw/line_style.go
- eventqueue/eventqueue.go
- mouse/mouse.go
- terminal/faketerm/faketerm.go
- terminal/termbox/termbox.go
- terminalapi/color_mode.go
- widgets/fakewidget/fakewidget_test.go
- widgets/gauge/gauge_test.go
- widgets/gauge/options.go
- Missing comments.
- Invalid comments.
- Stuttering public name.
- if<->else where not needed.
- changing variable kEv to keyEv since it triggers a link error related to Go names.
> Fixing lint errors.

- eventqueue/eventqueue.go
- eventqueue/eventqueue_test.go
- termdash.go
- termdash_test.go
- widgets/fakewidget/fakewidget.go
- widgets/fakewidget/fakewidget_test.go
- Adding a Controller object that allows triggering of redraw manually.
- The eventqueue now has an Empty() method to determine if it has been emptied.
- The fake widget can now display a custom text, needed for tests that want to verify if redraw happened or not.
- Improving test coverage in the fakewidget.
- Fixing two races in the termdash_test.
-- Race1: Waiting for event queue to empty before examining the fake terminal. This ensures that events were processed.
-- Race2: Moving the test of terminal resize into the group of tests that use the triggered redraw, as that is a convenient way of ensuring that we resize, then redraw and then compare the content.
Fixes #27
> Support for manually triggered redraw of terminal.

- draw/braille_line.go
- draw/line_style.go
- eventqueue/eventqueue_test.go
- termdashdemo/termdashdemo.go
- widgets/linechart/axes/label.go
- widgets/linechart/linechart.go
I fixed the errors except for gocyclo. Its an A+ grade now
> Partial Fix for #83 (Excluding Gocyclo)

- draw/border_test.go
- draw/line_style.go
I've added double-line style to termdash.
I created a test too, to ensure a border draws properly with two lines .
> Add Double Linestyle

- CHANGELOG.md
- widgets/linechart/axes/axes.go
- widgets/linechart/axes/axes_test.go
- widgets/linechart/axes/label_test.go
- widgets/linechart/axes/scale.go
- widgets/linechart/axes/scale_test.go
- widgets/linechart/linechart.go
- widgets/linechart/linechart_test.go
- widgets/linechart/linechartdemo/linechartdemo.go
- widgets/linechart/options.go
> Adding a LineChart option that switches the Y axis from anchored to adaptive.

- CHANGELOG.md
- container/draw.go
- doc/widget_development.md
- draw/testdraw/testdraw.go
- draw/text.go
- draw/text_test.go
- widgetapi/widgetapi.go
- widgets/barchart/barchart.go
- widgets/barchart/barchart_test.go
- widgets/gauge/gauge.go
- widgets/gauge/gauge_test.go
- widgets/linechart/linechart.go
- widgets/linechart/linechart_test.go
- widgets/sparkline/sparkline.go
- widgets/sparkline/sparkline_test.go
> Thread safe widgets

- CHANGELOG.md
- widgets/linechart/axes/label.go
- widgets/linechart/axes/label_test.go
- widgets/linechart/linechartdemo/linechartdemo.go
The LineChart widget now correctly places custom labels.
- The code incorrectly used label number rather than value position when
looking up custom labels.
Fixes #117
> Hotfix v0.6.1

- widgets/linechart/axes/axes.go
- widgets/linechart/axes/axes_test.go
- widgets/linechart/axes/scale.go
- widgets/linechart/axes/scale_test.go
- widgets/linechart/axes/value.go
- widgets/linechart/linechart.go
- widgets/linechart/linechart_test.go
- widgets/linechart/linechartdemo/linechartdemo.go
- widgets/linechart/zoom/zoom.go
- widgets/linechart/zoom/zoom_test.go
- stay unzoomed when we hit the largest view.
- correctly normalize zoom values when the base axis is in motion.
- test coverage for the edge cases.
- acquire mutex on mouse events.
Fixes #136
> Fixing invalid zooming behaviors.

- CHANGELOG.md
- align/align.go
- cell/cell.go
- cell/runewidth/runewidth.go
- cell/runewidth/runewidth_test.go
- draw/line_style.go
- draw/text.go
- widgets/donut/donut.go
- widgets/gauge/gauge.go
- widgets/sparkline/sparks.go
- widgets/text/line_scanner.go
- widgets/text/line_trim.go
These are characters used internally by termdash to draw boxes, indicate need to resize or scroll, etc.
Ensuring these are always considered half-width runes, even though they might be ambiguous in some locales.
Fixes #144
> Fixing the width of characters whose context is known.

- CHANGELOG.md
- widgets/barchart/barchart.go
- widgets/barchart/barchart_test.go
- widgets/barchart/options.go
- widgets/linechart/internal/axes/scale.go
- widgets/linechart/internal/axes/scale_test.go
- widgets/linechart/linechart.go
- widgets/linechart/linechart_test.go
- widgets/segmentdisplay/segmentdisplay_test.go
- widgets/sparkline/sparkline_test.go
Also better logging for out of bounds errors in LineChart.
Fixes #174.
> Prevent external mutation of data passed into widgets.

- CHANGELOG.md
- container/container_test.go
- container/draw.go
- container/draw_test.go
- container/grid/grid_test.go
- doc/widget_development.md
- internal/fakewidget/fakewidget.go
- internal/fakewidget/fakewidget_test.go
- termdash_test.go
- widgetapi/widgetapi.go
- widgets/barchart/barchart.go
- widgets/barchart/barchart_test.go
- widgets/button/button.go
- widgets/button/button_test.go
- widgets/donut/donut.go
- widgets/donut/donut_test.go
- widgets/gauge/gauge.go
- widgets/gauge/gauge_test.go
- widgets/linechart/linechart.go
- widgets/linechart/linechart_test.go
- widgets/segmentdisplay/segmentdisplay.go
- widgets/segmentdisplay/segmentdisplay_test.go
- widgets/sparkline/sparkline.go
- widgets/sparkline/sparkline_test.go
- widgets/text/text.go
- widgets/text/text_test.go
Currently contains only one signal - letting the widget know that its container is focused.
Fixes #18 
Fixes #178
> Provide metadata to widgets when drawing.

- CHANGELOG.md
- internal/numbers/numbers.go
- internal/numbers/numbers_test.go
- widgets/linechart/linechart.go
- widgets/linechart/linechart_test.go
This PR Fixes #184.
It will allow having _values_ on the line chart that will not be displayed if they are missing. To do so it will use the `math.NaN` float64 value.
If this is combined with adaptive Y-axis option, the graphs that have empty gaps and high values with small variance will be more accurate regarding the Y axis (because they will not start at 0).
In this example, we can see that we don't have metrics around 10:03-10:05 making the graph render values as 0 and making Y axis start at 0:
Instead of representing the missing metrics as 0, with this change and using `math.NaN`, the Y axis has a better range around the min and max values making the graph more accurate.
> Allow empty values on line chart

- .travis.yml
- CHANGELOG.md
- internal/draw/text.go
- internal/faketerm/diff.go
- internal/faketerm/faketerm.go
- internal/numbers/numbers.go
- internal/numbers/numbers_test.go
- internal/numbers/trig/trig.go
- internal/segdisp/sixteen/attributes.go
- internal/segdisp/sixteen/sixteen.go
- internal/wrap/wrap.go
- internal/wrap/wrap_test.go
- widgets/donut/circle.go
- widgets/donut/donut.go
- widgets/gauge/gauge.go
- widgets/linechart/internal/axes/scale.go
- widgets/segmentdisplay/segmentdisplay.go
- widgets/sparkline/sparks.go
- switching to math.Round and deleting out clone.
- switching all bytes.Buffer instances to strings.Builder.
> Advancing to Go1.10.

- CHANGELOG.md
- widgets/donut/donut.go
- widgets/donut/donut_test.go
- widgets/donut/donutdemo/donutdemo.go
Gives at least one empty line under the donut and above the text label.
Updates #85
> Guarantee some spacing between donut and its label.

- widgets/text/scroll.go
This change addresses the following compile error, reported by raspberry-pi golang compiler v1.12:
/home/pi/go/pkg/mod/github.com/mum4k/termdash@v0.9.0/widgets/text/scroll.go:119:29: constant 4294967295 overflows int
> Change MaxUint32 to MaxInt32 in scroll.go

- .travis.yml
- internal/numbers/numbers_test.go
- Updating a comment that was incorrectly indicating that test functions were related to Go 1.10.
> Advancing CI to Go 1.14.

- .travis.yml
- CHANGELOG.md
- terminal/tcell/tcell.go
- terminal/tcell/tcell_test.go
> Stub out tcell.NewScreen so tests can pass headless.

- .travis.yml
- CHANGELOG.md
- README.md
- advanced the CI Go versions up to Go 1.15.
- fixed the build status badge to correctly point to travis-ci.com instead of
travis-ci.org.
> Release v0.12.2

- README.md
- widgets/text/options.go
- widgets/text/text.go
#245 fixes this issue with windows consoles by adding option to switch the scroll runes on a text widget.
The option `text.ScrollRunes` accepts two rune parameters, up and down, the default runes are the same `⇧` and `⇩`.
An example of this which will draw correct scroll runes on windows
`text.New(text.RollContent(), text.WrapAtWords(), text.ScrollRunes('▲', '▼'))`
> Ability to swap scrolling runes 

- README.md
- cell/cell.go
- go.mod
- go.sum
- terminal/tcell/cell_options.go
- terminal/tcell/cell_options_test.go
- terminal/termbox/cell_options.go
- terminal/termbox/cell_options_test.go
- terminal/termbox/termbox.go
- widgets/text/textdemo/textdemo.go
This PR adds cell options for the font modifiers﻿ bold, italic, and underline.
`tcell` was upgraded 1.4.0.
Strikethrough cell option was added as a no-op until tcell is updated to v2.0.0. I figured it wasn't a good idea to upgrade tcell by a whole major version without testing.
Closes #251
> add font modifier cell options: bold, italic, underline.

- CHANGELOG.md
- container/container.go
- container/container_test.go
- container/focus.go
- container/focus_test.go
- container/options.go
- private/faketerm/diff.go
> Ability to move focus using keyboard.

- CHANGELOG.md
- container/container.go
- container/container_test.go
- private/fakewidget/fakewidget.go
- private/fakewidget/fakewidget_test.go
- termdash_test.go
- widgetapi/widgetapi.go
- widgets/barchart/barchart.go
- widgets/button/button.go
- widgets/button/button_test.go
- widgets/donut/donut.go
- widgets/donut/donut_test.go
- widgets/gauge/gauge.go
- widgets/gauge/gauge_test.go
- widgets/heatmap/heatmap.go
- widgets/linechart/linechart.go
- widgets/linechart/linechart_test.go
- widgets/segmentdisplay/segmentdisplay.go
- widgets/segmentdisplay/segmentdisplay_test.go
- widgets/sparkline/sparkline.go
- widgets/text/text.go
- widgets/text/text_test.go
- widgets/textinput/textinput.go
- widgets/textinput/textinput_test.go
Initially lets the widget know if it container was focused at the time of the event.
Works on #243.
> Send metadata about events to widgets.

- CHANGELOG.md
- container/container.go
- container/container_test.go
- container/focus.go
- container/focus_test.go
- container/options.go
Containers can register into separate focus groups and specific keyboard keys can be configured to move the focus within each focus group.
Works on #243
> Support closed focus groups.

- CHANGELOG.md
- private/canvas/canvas.go
> Termdash no longer crashes with tcell when terminal window downsizes.

- widgets/text/options.go
- widgets/text/text.go
- widgets/text/text_test.go
See issue #293 where memory and performance can degrade with a high number of lines written to the Text widget. 
This is a very simplistic implementation to limit the possible length the text buffer can grow to with the `maxContent` option. 
Default value of -1 means there's no limit and therefore behaviour should remain standard.
It has been working in our test app and allows the use of the Text widget to monitor logs (ie tail) and therefore doesn't bloat over time, but happy to adjust as required.
> Implements a buffer limit for the Text widget

- CHANGELOG.md
- private/runewidth/runewidth.go
- private/runewidth/runewidth_test.go
- widgets/text/options.go
- widgets/text/text.go
- widgets/text/text_test.go
- widgets/text/textdemo/textdemo.go
See issue #293 where memory and performance can degrade with a high number of lines written to the Text widget. 
This is a very simplistic implementation to limit the possible length the text buffer can grow to with the `maxContent` option. 
Default value of -1 means there's no limit and therefore behaviour should remain standard.
It has been working in our test app and allows the use of the Text widget to monitor logs (ie tail) and therefore doesn't bloat over time, but happy to adjust as required.
> Implements a buffer limit for the Text widget.

- widgets/textinput/editor.go
- widgets/textinput/editor_test.go
- widgets/textinput/options.go
- widgets/textinput/textinput.go
- widgets/textinput/textinputdemo/textinputdemo.go
This PR adds an `onChange` option to the TextInput widget. This is an event handler similar to the existing `OnSubmit`, it is called whenever a character is inserted or deleted from the TextInput's text content.
Rudimentary tests have been written and an example of it's usage is given in `textinputdemo.go`.
> Add OnChange handler to the TextInput widget

- container/container_test.go
- container/focus_test.go
- keyboard/keyboard.go
- terminal/tcell/event.go
- terminal/tcell/event_test.go
- widgets/textinput/formdemo/formdemo.go
This implements "Backtab" (a.k.a. Shift+Tab) as a supported keystroke for tcell widgets. Uses backtab in a few tests and demos as makes sense.
> Implement backtab for tcell widgets
