widgets/barchart/barchart.go, widgets/barchart/barchart_test.go, widgets/barchart/barchartdemo/barchartdemo.go, widgets/barchart/options.go, widgets/text/line_trim.go, widgets/text/line_trim_test.go
Including a demo.
Also rerunning the script which adds licences to files.
Fixes #8
=> Implementing a BarChart widget.

widgets/sparkline/options.go, widgets/sparkline/sparkline.go, widgets/sparkline/sparkline_test.go, widgets/sparkline/sparklinedemo/sparklinedemo.go, widgets/sparkline/sparks.go, widgets/sparkline/sparks_test.go
=> Implementing the SparkLine widget.

canvas/braille/testbraille/testbraille.go, draw/braille_line.go, draw/braille_line_test.go
=>  Function that draws lines on a braille canvas.

cell/color.go, cell/color_test.go, terminal/termbox/cell_options.go, terminal/termbox/cell_options_test.go, terminal/termbox/color_mode.go, terminal/termbox/termbox.go, terminalapi/color_mode.go
- Documenting color modes.
- Providing helper functions to set colors in different formats.
- Allowing users to set other than the 8 system colors.
Fixes #66
=> Support for 256 colors.

area/area.go, area/area_test.go, container/container.go, container/container_test.go, container/draw.go, container/draw_test.go, container/focus_test.go, container/options.go, container/traversal_test.go, termdash_test.go, widgets/barchart/barchartdemo/barchartdemo.go, widgets/gauge/demo/gaugedemo.go, widgets/linechart/linechartdemo/linechartdemo.go, widgets/sparkline/sparklinedemo/sparklinedemo.go, widgets/text/demo/textdemo.go
=> Variable container splits.

widgets/text/text.go, widgets/text/text_test.go
added comments in exported functions and removed redundant checks as golint suggestion.
fixes  #76
=> cleanup lint issues

draw/border_test.go, draw/line_style.go
Issue #81 Unicode rounded borders.
=> Added LineStyleRound

CHANGELOG.md, termdash_test.go
=> Increasing the time allowed for Run to finish its operation.

CHANGELOG.md, terminal/termbox/termbox.go, terminal/termbox/termbox_test.go
=> 256 color default

draw/vertical_text.go, draw/vertical_text_test.go
=> Function that draws text in vertical columns.

CHANGELOG.md, draw/testdraw/testdraw.go, widgets/linechart/axes/axes.go, widgets/linechart/axes/axes_test.go, widgets/linechart/axes/label.go, widgets/linechart/axes/label_test.go, widgets/linechart/linechart.go, widgets/linechart/linechart_test.go, widgets/linechart/options.go
=> Linechart now supports vertical label orientation under the X axis.

CHANGELOG.md, termdashdemo/termdashdemo.go, widgets/linechart/linechart.go, widgets/linechart/linechart_test.go, widgets/linechart/linechartdemo/linechartdemo.go, widgets/linechart/options.go
=> Allow users to provide custom Y axis scale for the LineChart.

CHANGELOG.md, termdashdemo/termdashdemo.go, widgets/barchart/barchart.go, widgets/barchart/barchart_test.go, widgets/barchart/barchartdemo/barchartdemo.go, widgets/barchart/options.go, widgets/gauge/gauge.go, widgets/gauge/gauge_test.go, widgets/gauge/gaugedemo/gaugedemo.go, widgets/gauge/options.go, widgets/sparkline/options.go, widgets/sparkline/sparkline.go, widgets/sparkline/sparkline_test.go, widgets/sparkline/sparklinedemo/sparklinedemo.go, widgets/text/options.go, widgets/text/text.go, widgets/text/text_test.go, widgets/text/textdemo/textdemo.go
=> Constructors of all widgets now return an error.

CHANGELOG.md, widgets/text/text.go, widgets/text/text_test.go, widgets/text/write_options.go
=> Adding Text Write option that atomically replaces the text content.

widgets/linechart/linechart_test.go, widgets/linechart/options.go
=> Make the Y axis adaptive when custom scale is provided

widgets/linechart/zoom/zoom.go, widgets/linechart/zoom/zoom_test.go
=> Don't zoom when only a single column was highlighted.

widgets/linechart/zoom/zoom.go, widgets/linechart/zoom/zoom_test.go
=> Roll the zoom with the axis when XAxisUnscaled is provided.

CHANGELOG.md, container/container.go, container/container_test.go, termdash_test.go, widgetapi/widgetapi.go, widgets/barchart/barchart.go, widgets/barchart/barchart_test.go, widgets/donut/donut.go, widgets/donut/donut_test.go, widgets/fakewidget/fakewidget.go, widgets/fakewidget/fakewidget_test.go, widgets/gauge/gauge.go, widgets/gauge/gauge_test.go, widgets/segmentdisplay/segmentdisplay.go, widgets/segmentdisplay/segmentdisplay_test.go, widgets/sparkline/sparkline.go, widgets/sparkline/sparkline_test.go, widgets/text/text.go, widgets/text/text_test.go
=> Allow widgets to subscribe to global keyboard events

CHANGELOG.md, widgets/barchart/barchart.go, widgets/barchart/barchart_test.go, widgets/barchart/barchartdemo/barchartdemo.go, widgets/sparkline/sparkline.go, widgets/sparkline/sparkline_test.go, widgets/sparkline/sparklinedemo/sparklinedemo.go
=> Adding ValueCapacity method to BarChart and SparkLine.

CHANGELOG.md, README.md, container/grid/grid.go, container/grid/grid_test.go, termdashdemo/termdashdemo.go
Fixes #171 
Adds a grid.Builder which allows to iteratively add rows and columns.
Also updating Termdashdemo to demonstrate the same result using both the APIs.
=> A new API for building terminal layouts.

CHANGELOG.md, container/container.go, container/container_test.go, container/focus.go
=> Correctly track container focus when the terminal size increases.

CHANGELOG.md, README.md, container/container.go, container/container_test.go, container/focus.go, container/focus_test.go, container/options.go, container/traversal.go, container/traversal_test.go, termdash.go, termdash_test.go, termdashdemo/termdashdemo.go
=> Container now supports dynamic layout changes.

CHANGELOG.md, widgets/segmentdisplay/segment_area.go, widgets/segmentdisplay/segmentdisplay.go, widgets/segmentdisplay/segmentdisplay_test.go
Works on #65 (needed in the demo).
=> SegmentDisplay now reports its capacity.

CHANGELOG.md, internal/area/area.go, internal/area/area_test.go, widgets/donut/donut.go, widgets/donut/donut_test.go, widgets/donut/donutdemo/donutdemo.go, widgets/donut/options.go
=> Support a text label under the Donut widget.

README.md
I've made the PR against master branch because on `devel` branch the Readme is not updated. Hope this is not a problem, if you prefer I can wait and make the Pr to devel branch when this is updated with `master` changes.
Thanks!
=> Add grafterm description on readme

CHANGELOG.md, widgets/button/button.go, widgets/textinput/textinput.go
=> Release widget's mutex before activating external callback.

CHANGELOG.md, container/grid/grid.go, container/grid/grid_test.go
=> Support fixed size splits in the grid API.

widgets/button/options.go
=> Fixing typo in a comment.

CHANGELOG.md, README.md, widgets/text/options.go, widgets/text/text.go, widgets/text/text_test.go
With added test coverage.
Fixes #245
=> Ability to swap Scroll runes.

CHANGELOG.md, go.mod, go.sum
=> Upgrading all dependencies.

CHANGELOG.md, container/grid/grid_test.go, termdash_test.go, termdashdemo/termdashdemo.go, terminal/termbox/termbox.go, widgets/barchart/barchartdemo/barchartdemo.go, widgets/button/buttondemo/buttondemo.go, widgets/donut/donutdemo/donutdemo.go, widgets/gauge/gaugedemo/gaugedemo.go, widgets/linechart/linechartdemo/linechartdemo.go, widgets/segmentdisplay/segmentdisplaydemo/segmentdisplaydemo.go, widgets/sparkline/sparklinedemo/sparklinedemo.go, widgets/text/textdemo/textdemo.go, widgets/textinput/textinputdemo/textinputdemo.go
=> Making tcell the default in all demos and examples.

cell/cell.go, cell/cell_test.go, terminal/tcell/cell_options.go, terminal/tcell/cell_options_test.go, terminal/termbox/cell_options.go, terminal/termbox/cell_options_test.go
=> add remaining font modifiers: strikethrough, inverse, blink

.gitignore, widgets/heatmap/heatmap.go, widgets/heatmap/heatmap_test.go, widgets/heatmap/heatmapdemo/heatmapdemo.go, widgets/heatmap/internal/README.md, widgets/heatmap/internal/axes/axes.go, widgets/heatmap/internal/axes/axes_test.go, widgets/heatmap/internal/axes/label.go, widgets/heatmap/internal/axes/label_test.go, widgets/heatmap/options.go
Most of the design refers to the implementation of LineChart, but some simplifications have been made, such as:
- Remove some options
- Zooming is not supported (I don't think it is necessary)
- ...
Feel free to ask me if you have any questions :)
=> Design APIs of the HeatMap widget

CHANGELOG.md, container/container.go, container/container_test.go, widgetapi/widgetapi.go
=> Allow widgets to request keyboard events exclusively.

CHANGELOG.md, container/focus.go, container/focus_test.go, container/options.go
=> Containers can request to be skipped when focus is moved using keyboard keys.

CHANGELOG.md, widgets/textinput/options.go, widgets/textinput/textinput.go, widgets/textinput/textinput_test.go
=> Textinput can request keyboard exclusively.

CHANGELOG.md, container/focus_test.go, container/options.go
=> Container option that sets the container as focused.

CHANGELOG.md, widgets/textinput/options.go, widgets/textinput/textinput.go, widgets/textinput/textinput_test.go
=> DefaultText option for textinput.

CHANGELOG.md, widgets/button/button.go, widgets/button/button_test.go
=> Allow updating the callback function on an existing button instance.

CHANGELOG.md, container/container_test.go, container/draw.go, container/draw_test.go, container/options.go
Introduce options for setting border title color and border title focus color. 
Fixes #73
=> Add support for setting of different colors for container's border and title

README.md
+ added "ali" as reference in projects
=> Update README.md (+ reference "ali")

.travis.yml
=> Temporarily disable line coverage.

.travis.yml
=> Temporarily disable older golang builds and gofmt step.

widgets/textinput/editor_test.go
=> Fix tests in editor_test.go.

widgets/textinput/options.go
=> Fix GoLint issue.

go.mod
=> Updating go.mod.

README.md
Suimon is a powerful command line tool designed to provide detailed dashboards for monitoring the SUI network.
https://github.com/bartosian/suimon
=> Added project example which uses Termdash
